#!/usr/bin/env bash
# =============================================================================
# setup-agent-envs.sh
# -----------------------------------------------------------------------------
# Materialize per-app env files from host environment variables.
#
#   WEB_*    → apps/web/.env.local   (Next.js reads this automatically)
#   MOBILE_* → apps/mobile/.env       (Expo reads this automatically)
#
# Prefixes are stripped when written. For example:
#
#   export WEB_MONGODB_URI="mongodb+srv://..."
#   export MOBILE_EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_..."
#
# yields:
#
#   apps/web/.env.local:       MONGODB_URI=mongodb+srv://...
#   apps/mobile/.env:          EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...
#
# This script is called by the `bootstrap-env` skill and is safe to run
# repeatedly — each invocation rewrites both files from scratch.
#
# See .cursor/skills/bootstrap-env/SKILL.md for full agent instructions.
# =============================================================================

set -euo pipefail

# Resolve the directory this script lives in so we can be called from anywhere.
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$_SCRIPT_DIR"

# Internal variables are intentionally underscore-prefixed so they do not
# collide with WEB_* / MOBILE_* host variables that the script materializes.
_WEB_FILE="apps/web/.env.local"
_MOBILE_FILE="apps/mobile/.env"

# -----------------------------------------------------------------------------
# Required variable lists (enforced; missing ones abort the script).
# Keep these in sync with .cursor/skills/bootstrap-env/SKILL.md.
# -----------------------------------------------------------------------------
REQUIRED_WEB_VARS=(
  "WEB_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
  "WEB_CLERK_SECRET_KEY"
  "WEB_CLERK_WEBHOOK_SECRET"
  "WEB_MONGODB_URI"
  "WEB_OPENAI_API_KEY"
  "WEB_NEXT_PUBLIC_APP_URL"
  "WEB_R2_ACCOUNT_ID"
  "WEB_R2_ACCESS_KEY_ID"
  "WEB_R2_SECRET_ACCESS_KEY"
  "WEB_R2_BUCKET"
  "WEB_R2_PUBLIC_URL"
)

REQUIRED_MOBILE_VARS=(
  "MOBILE_EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY"
  "MOBILE_EXPO_PUBLIC_API_URL"
)

# -----------------------------------------------------------------------------
# Optional variables (recognised but not enforced).
#
# Notifications: when these are unset the web dispatcher silently no-ops the
# matching channel rather than throwing — push without EXPO_ACCESS_TOKEN
# still works (anonymous Expo rate limit), email without RESEND_API_KEY
# disables outbound mail entirely.
#
#   WEB_RESEND_API_KEY       — Resend transactional API key
#   WEB_RESEND_FROM          — Default From address (e.g. "Sous <…>" )
#   WEB_EXPO_ACCESS_TOKEN    — Expo push access token (raises rate limits)
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

# Print a coloured status line without depending on tput; keep it ASCII-safe.
log() {
  printf '[setup-agent-envs] %s\n' "$*"
}

fail() {
  printf '[setup-agent-envs] ERROR: %s\n' "$*" >&2
  exit 1
}

# Ensure the two app directories exist before we try to write into them.
require_dir() {
  local dir="$1"
  [ -d "$dir" ] || fail "Expected directory not found: $dir (run from monorepo root)"
}

# Enforce that every name in the list is present and non-empty in the env.
check_required() {
  local label="$1"
  shift
  local missing=()
  local name
  for name in "$@"; do
    if [ -z "${!name-}" ]; then
      missing+=("$name")
    fi
  done

  if [ "${#missing[@]}" -gt 0 ]; then
    log "Missing required $label variable(s):"
    for name in "${missing[@]}"; do
      printf '  - %s\n' "$name" >&2
    done
    fail "Aborting. Please inject the missing variables and re-run."
  fi
}

# Write a single KEY=VALUE line, escaping the value for safety.
#
# We wrap the value in double quotes and escape embedded backslashes, dollar
# signs, double quotes, and backticks so a value like
#   postgres://user:p@ss"word$@/db
# round-trips intact through dotenv parsers (Next.js / Expo both use dotenv).
write_kv() {
  local file="$1"
  local key="$2"
  local value="$3"

  local escaped="$value"
  escaped="${escaped//\\/\\\\}"
  escaped="${escaped//\$/\\\$}"
  escaped="${escaped//\`/\\\`}"
  escaped="${escaped//\"/\\\"}"

  printf '%s="%s"\n' "$key" "$escaped" >> "$file"
}

# Emit a stable banner so humans know the file is auto-generated.
write_banner() {
  local file="$1"
  local app="$2"
  local source_prefix="$3"

  {
    printf '# ---------------------------------------------------------------\n'
    printf '# %s — generated by setup-agent-envs.sh\n' "$app"
    printf '# Source: %s* environment variables on the cloud agent host.\n' "$source_prefix"
    printf '# Do NOT hand-edit. Re-run ./setup-agent-envs.sh to refresh.\n'
    printf '# Generated at %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    printf '# ---------------------------------------------------------------\n'
  } > "$file"
}

# Walk every env var starting with the given prefix, strip the prefix, and
# append each one to the target file. Returns the count via stdout.
materialize_prefixed_vars() {
  local prefix="$1"
  local file="$2"
  local count=0

  # `compgen -v` lists every shell variable name. Filter by prefix and write
  # each pair. Use a while-read loop so we don't blow up on odd values.
  local name
  while IFS= read -r name; do
    case "$name" in
      "${prefix}"*)
        local stripped="${name#${prefix}}"
        # Skip internal bash variables that happen to start with the prefix
        # (e.g. WEB_* would never collide, but future-proof against shells
        # that populate upper-case readonly vars).
        [ -z "$stripped" ] && continue
        local value="${!name-}"
        write_kv "$file" "$stripped" "$value"
        count=$((count + 1))
        ;;
    esac
  done < <(compgen -v | sort)

  printf '%d\n' "$count"
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

log "Bootstrapping per-app env files in $_SCRIPT_DIR"

require_dir "apps/web"
require_dir "apps/mobile"

check_required "WEB_"    "${REQUIRED_WEB_VARS[@]}"
check_required "MOBILE_" "${REQUIRED_MOBILE_VARS[@]}"

# --- Web ---------------------------------------------------------------------
log "Writing $_WEB_FILE"
write_banner "$_WEB_FILE" "Sous Web (Next.js)" "WEB_"
_WEB_COUNT="$(materialize_prefixed_vars "WEB_" "$_WEB_FILE")"
log "  wrote $_WEB_COUNT variable(s) to $_WEB_FILE"

# --- Mobile ------------------------------------------------------------------
log "Writing $_MOBILE_FILE"
write_banner "$_MOBILE_FILE" "Sous Mobile (Expo)" "MOBILE_"
_MOBILE_COUNT="$(materialize_prefixed_vars "MOBILE_" "$_MOBILE_FILE")"
log "  wrote $_MOBILE_COUNT variable(s) to $_MOBILE_FILE"

log "Done. Apps are now configured."
log "Next: run 'npm install' from the monorepo root."
